// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLI-stg407xJTltHV5fbH9T-Yd6LYELOA',
    appId: '1:1093308923160:web:32a5fe43cdba0286f2726d',
    messagingSenderId: '1093308923160',
    projectId: 'flutterfirenyimas',
    authDomain: 'flutterfirenyimas.firebaseapp.com',
    storageBucket: 'flutterfirenyimas.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmy1vyFPIovWdRUOoP4srnIZaRN-8DmvU',
    appId: '1:1093308923160:android:540ebbf47d46f9b2f2726d',
    messagingSenderId: '1093308923160',
    projectId: 'flutterfirenyimas',
    storageBucket: 'flutterfirenyimas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf-qhjNpsK3o0-dfrZsOfS9MKDI0H6eXU',
    appId: '1:1093308923160:ios:24356117816370edf2726d',
    messagingSenderId: '1093308923160',
    projectId: 'flutterfirenyimas',
    storageBucket: 'flutterfirenyimas.appspot.com',
    iosBundleId: 'com.example.flutterlist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf-qhjNpsK3o0-dfrZsOfS9MKDI0H6eXU',
    appId: '1:1093308923160:ios:24356117816370edf2726d',
    messagingSenderId: '1093308923160',
    projectId: 'flutterfirenyimas',
    storageBucket: 'flutterfirenyimas.appspot.com',
    iosBundleId: 'com.example.flutterlist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLI-stg407xJTltHV5fbH9T-Yd6LYELOA',
    appId: '1:1093308923160:web:9678fba12757da7ef2726d',
    messagingSenderId: '1093308923160',
    projectId: 'flutterfirenyimas',
    authDomain: 'flutterfirenyimas.firebaseapp.com',
    storageBucket: 'flutterfirenyimas.appspot.com',
  );
}
