// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjxNZMW66VL9plVvOsU7bhjjArXAFW44U',
    appId: '1:693805674744:web:0e25f34bff8019548f0b0d',
    messagingSenderId: '693805674744',
    projectId: 'notes-4a06b',
    authDomain: 'notes-4a06b.firebaseapp.com',
    storageBucket: 'notes-4a06b.appspot.com',
    measurementId: 'G-CLEGTKRQB9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAepr8ETnyZ8HkKMzBvZCc1KOLiCPwQ6Ps',
    appId: '1:693805674744:android:00c5adf2a7e09a2f8f0b0d',
    messagingSenderId: '693805674744',
    projectId: 'notes-4a06b',
    storageBucket: 'notes-4a06b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyrjc8RT9UwVhZo_AJkAAxnnNKN4JLdyk',
    appId: '1:693805674744:ios:d92c33342cf711da8f0b0d',
    messagingSenderId: '693805674744',
    projectId: 'notes-4a06b',
    storageBucket: 'notes-4a06b.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyrjc8RT9UwVhZo_AJkAAxnnNKN4JLdyk',
    appId: '1:693805674744:ios:d92c33342cf711da8f0b0d',
    messagingSenderId: '693805674744',
    projectId: 'notes-4a06b',
    storageBucket: 'notes-4a06b.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjxNZMW66VL9plVvOsU7bhjjArXAFW44U',
    appId: '1:693805674744:web:da8b1ed38f5330528f0b0d',
    messagingSenderId: '693805674744',
    projectId: 'notes-4a06b',
    authDomain: 'notes-4a06b.firebaseapp.com',
    storageBucket: 'notes-4a06b.appspot.com',
    measurementId: 'G-2TBDBWJVDT',
  );
}
